language: go

go:
  - 1.11.x
  - stable
  - master

matrix:
  # Failing on the development version of Go isn't too bad.
  allow_failures:
    - go: master

env:
  - GO111MODULE=on

# Override Travis's default 'go get' step, since we use Go modules
install:
  - go mod download


before_script:
  # Fetch refs for linter
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch

  # Install golangci-lint
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.2

script:
  - go build ./...

  # Lint changed code
  - if [[ "$TRAVIS_COMMIT_RANGE" != "" ]]; then commit_range=${TRAVIS_COMMIT_RANGE/.../..} && git diff $commit_range > /dev/null && base_rev=$commit_range || true; fi
  - if [[ "$base_rev" = "" ]]; then base_rev='origin/master'; fi && echo "Linting changes between/since $base_rev"
  - golangci-lint run --new-from-rev $base_rev

  # Race tests (can't be done with covermode=count)
  - go test -v -race

  # Coverage with covermode=count
  - go test -v -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)
